-- Workshop Hub — collection/delivery request on public chain bookings, with
-- a transport approve/decline handled by email
-- Run this in the Supabase SQL editor, after migration_052.
--
-- Timing Chain Specialists customers booking a chain job can ask us to
-- collect the vehicle (and optionally deliver it back), which needs a real
-- transport run booked in — so unlike a normal booking request, this one
-- also goes out to the transport contact for a yes/no. Their response is
-- recorded here and only ever notifies the office (see
-- sendTransportResponseNotification) — never the customer directly, who
-- only hears back once office makes the final accept/decline call, same as
-- every other booking request.
--
-- transport_token follows the exact same pattern as job_approvals.token —
-- a random, unguessable value that scopes the public transport-response
-- link to exactly one request, generated by the database rather than the
-- app so it's never left unset by an insert that forgets it.

alter table booking_requests add column if not exists transport_type text not null default 'none'
  check (transport_type in ('none', 'collect', 'collect_deliver'));

-- Informational only (see PublicBooking.jsx / api/public/book) — never used
-- to block extra days on the public calendar. Office sets the real span via
-- the existing bookings.days field when they convert an approved request.
alter table booking_requests add column if not exists estimated_days integer;

alter table booking_requests add column if not exists transport_status text not null default 'not_required'
  check (transport_status in ('not_required', 'pending', 'approved', 'declined'));

alter table booking_requests add column if not exists transport_token text unique
  default replace(gen_random_uuid()::text, '-', '');

alter table booking_requests add column if not exists transport_responded_at timestamptz;

-- A named transport contact already existed (transport_contact_name/phone,
-- used for the WhatsApp price-check button) but had no email — needed here
-- since the collect/deliver request goes out automatically rather than via
-- a manually-composed message.
alter table settings add column if not exists transport_contact_email text not null default '';
